{{- if not .Values.existingSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-uptimerobot-exporter.secretName" . }}
  labels:
    {{- include "prometheus-uptimerobot-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  uptimerobot-api-key: {{ required "A UptimeRobot API Key is required" .Values.uptimerobot.apiKey | b64enc }}
{{- end -}}